# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: doctordeng.github.io
date_format: "ordinal"
title: DoctorDeng
subtitle: "书是个好东西哈"
description: "小邓的个人博客"
keywords: DoctorDeng
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/DoctorDeng/DoctorDeng.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: DoctorDeng
organization: 无业游民
organization_url: https://github.com/DoctorDeng
location: 北京-中国
email: vip.doctordeng@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: DoctorDeng
#douban_username: freedim
#facebook_username: mzlogin
#weibo_username: mzlogin
#zhihu_username: mzlogin
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, laibili
comments_provider: laibili
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: doctordeng
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: false
#duoshuo_share: true

laibili_uid : MTAyMC8zMTU1NS84MTE5
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-108817326-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_server_keywords: [Spring Boot, Spring Cloud, Redis, Kafka, Nacos]
skill_know_keywords: [Kubernetes, Docker, Jenkins, Shell, Linux]
